<div>
  <div class="form-group">
    <label for="client_id" class="col-sm-2 control-label">Cliente</label>
    <div class="form-group">
    <select type="text" class="form-control" id="client_id" name="client_id">
      <option value="">Selecione o cliente</option>
      @foreach ($clients as $client)
          <option value="{{ @$client->id }}" {{ @$project->client_id == @$client->id ? 'selected' : '' }}>{{ @$client->name }}</option>
      @endforeach
    </select>
  </div>
<br>
  <div class="row">
    <div class="col">
      <label for="code" class="col-sm-8 control-label">Código do País</label>
      <select type="text" class="form-control" id="code" name="code">
        <option value="">Selecione o código do país</option>
        @foreach ($clients as $client)
            <option value="{{ $client->id }}" {{ @$project->client_id == $client->id ? 'selected' : '' }}>{{ @$project->code }}</option>
            <option value='93-Afeganistão'>Afeganistão</option>
            <option value='27-África do Sul'>África do Sul</option>
            <option value='355-Albânia'>Albânia</option>
            <option value='49-Alemanha'>Alemanha</option>
            <option value='376-Andorra'>Andorra</option>
            <option value='244-Angola'>Angola</option>
            <option value='1-Anguila'>Anguila</option>
            <option value='1-Antígua e Barbuda'>Antígua e Barbuda</option>
            <option value='599-Antilhas Neerlandesas'>Antilhas Neerlandesas</option>
            <option value='966-Arábia Saudita'>Arábia Saudita</option>
            <option value='213-Argélia'>Argélia</option>
            <option value='54-Argentina'>Argentina</option>
            <option value='374-Armênia'>Armênia</option>
            <option value='297-Aruba'>Aruba</option>
            <option value='61-Austrália'>Austrália</option>
            <option value='43-Áustria'>Áustria</option>
            <option value='994-Azerbaijão'>Azerbaijão</option>
            <option value='1-Bahamas'>Bahamas</option>
            <option value='880-Bangladexe'>Bangladexe</option>
            <option value='1-Barbados'>Barbados</option>
            <option value='973-Barém'>Barém</option>
            <option value='32-Bélgica'>Bélgica</option>
            <option value='501-Belize'>Belize</option>
            <option value='22-9Benim'>Benim</option>
            <option value='1-Bermudas'>Bermudas</option>
            <option value='375-Bielorrússia'>Bielorrússia</option>
            <option value='591-Bolívia'>Bolívia</option>
            <option value='387-Bósnia e Herzegovina'>Bósnia e Herzegovina</option>
            <option value='267-Botsuana'>Botsuana</option>
            <option value='55-Brasil'>Brasil</option>
            <option value='673-Brunei'>Brunei</option>
            <option value='359-Bulgária'>Bulgária</option>
            <option value='226-Burquina Fasso'>Burquina Fasso</option>
            <option value='257-Burundi'>Burundi</option>
            <option value='975-Butão'>Butão</option>
            <option value='238-Cabo Verde'>Cabo Verde</option>
            <option value='237-Camarões'>Camarões</option>
            <option value='855-Camboja'>Camboja</option>
            <option value='1-Canadá'>Canadá</option>
            <option value='974-Catar'>Catar</option>
            <option value='7-Cazaquistão'>Cazaquistão</option>
            <option value='235-Chade'>Chade</option>
            <option value='56-Chile'>Chile</option>
            <option value='86-China'>China</option>
            <option value='357-Chipre'>Chipre</option>
            <option value='57-Colômbia'>Colômbia</option>
            <option value='269-Comores'>Comores</option>
            <option value='242-Congo-Brazavile'>Congo-Brazavile</option>
            <option value='243-ongo-Quinxassa'>Congo-Quinxassa</option>
            <option value='850-Coreia do Norte'>Coreia do Norte</option>
            <option value='82-Coreia do Sul'>Coreia do Sul</option>
            <option value='225-Costa do Marfim'>Costa do Marfim</option>
            <option value='506-Costa Rica'>Costa Rica</option>
            <option value='385-Croácia'>Croácia</option>
            <option value='53-Cuba'>Cuba</option>
            <option value='45-Dinamarca'>Dinamarca</option>
            <option value='253-Djibuti'>Djibuti</option>
            <option value='1-Dominica'>Dominica</option>
            <option value='20-Egipto'>Egipto</option>
            <option value='503-El Salvador'>El Salvador</option>
            <option value='971-Emirados Árabes Unidos'>Emirados Árabes Unidos</option>
            <option value='593-Equador'>Equador</option>
            <option value='291-Eritreia'>Eritreia</option>
            <option value='421-Eslováquia'>Eslováquia</option>
            <option value='386-Eslovénia'>Eslovénia</option>
            <option value='34-Espanha'>Espanha</option>
            <option value='268-Essuatíni'>Essuatíni</option>
            <option value='691-Estados Federados da Micronésia'>Estados Federados da Micronésia</option>
            <option value='1-Estados Unidos'>Estados Unidos</option>
            <option value='372-Estónia'>Estónia</option>
            <option value='251-Etiópia'>Etiópia</option>
            <option value='679-Fiji'>Fiji</option>
            <option value='63-Filipinas'>Filipinas</option>
            <option value='358-Finlândia'>Finlândia</option>
            <option value='33-França'>França</option>
            <option value='241-Gabão'>Gabão</option>
            <option value='220-Gâmbia'>Gâmbia</option>
            <option value='233-Gana'>Gana</option>
            <option value='995-Geórgia'>Geórgia</option>
            <option value='350-Gibraltar'>Gibraltar</option>
            <option value='1-Granada'>Granada</option>
            <option value='30-Grécia'>Grécia</option>
            <option value='299-Groenlândia'>Groenlândia</option>
            <option value='590-Guadalupe'>Guadalupe</option>
            <option value='1-Guam'>Guam</option>
            <option value='502-Guatemala'>Guatemala</option>
            <option value='592-Guiana'>Guiana</option>
            <option value='594-Guiana Francesa'>Guiana Francesa</option>
            <option value='224-Guiné'>Guiné</option>
            <option value='240-Guiné Equatorial'>Guiné Equatorial</option>
            <option value='245-Guiné-Bissau'>Guiné-Bissau</option>
            <option value='509-Haiti'>Haiti</option>
            <option value='504-Honduras'>Honduras</option>
            <option value='852-Hong Kong'>Hong Kong</option>
            <option value='36-Hungria'>Hungria</option>
            <option value='967-Iêmen'>Iêmen</option>
            <option value='672-Ilha Christmas'>Ilha Christmas</option>
            <option value='672-Ilha Heard e Ilhas McDonald'>Ilha Heard e Ilhas McDonald</option>
            <option value='672-Ilha Norfolque'>Ilha Norfolque</option>
            <option value='1-Ilhas Caimã'>Ilhas Caimã</option>
            <option value='672-Ilhas Cocos'>Ilhas Cocos</option>
            <option value='682-Ilhas Cook'>Ilhas Cook</option>
            <option value='298-Ilhas Féroe'>Ilhas Féroe</option>
            <option value='500-Ilhas Malvinas'>Ilhas Malvinas</option>
            <option value='1-Ilhas Marianas do Norte'>Ilhas Marianas do Norte</option>
            <option value='692-Ilhas Marshall'>Ilhas Marshall</option>
            <option value='677-Ilhas Salomão'>Ilhas Salomão</option>
            <option value='1-Ilhas Virgens Americanas'>Ilhas Virgens Americanas</option>
            <option value='1-Ilhas Virgens Britânicas'>Ilhas Virgens Britânicas</option>
            <option value='91-Índia'>Índia</option>
            <option value='62-Indonésia'>Indonésia</option>
            <option value='98-Irã'>Irã</option>
            <option value='964-Iraque'>Iraque</option>
            <option value='353-Irlanda'>Irlanda</option>
            <option value='354-Islândia'>Islândia</option>
            <option value='972-Israel'>Israel</option>
            <option value='39-Itália'>Itália</option>
            <option value='1-Jamaica'>Jamaica</option>
            <option value='81-Japão'>Japão</option>
            <option value='962-Jordânia'>Jordânia</option>
            <option value='383-Kosovo'>Kosovo</option>
            <option value='965-Kuwait'>Kuwait</option>
            <option value='247-lag of Ascension Island.svg Ascensão'>lag of Ascension Island.svg Ascensão</option>
            <option value='856-Laos'>Laos</option>
            <option value='266-Lesoto'>Lesoto</option>
            <option value='371-Letônia'>Letônia</option>
            <option value='961-Líbano'>Líbano</option>
            <option value='231-Libéria'>Libéria</option>
            <option value='218-Líbia'>Líbia</option>
            <option value='423-Liechtenstein'>Liechtenstein</option>
            <option value='370-Lituânia'>Lituânia</option>
            <option value='352-Luxemburgo'>Luxemburgo</option>
            <option value='853-Macau'>Macau</option>
            <option value='389-Macedônia do Norte'>Macedônia do Norte</option>
            <option value='261-Madagascar'>Madagascar</option>
            <option value='269-Maiote'>Maiote</option>
            <option value='60-Malásia'>Malásia</option>
            <option value='265-Maláui'>Maláui</option>
            <option value='960-Maldivas'>Maldivas</option>
            <option value='223-Mali'>Mali</option>
            <option value='356-Malta'>Malta</option>
            <option value='212-Marrocos'>Marrocos</option>
            <option value='596-Martinica'>Martinica</option>
            <option value='230-Maurícia'>Maurícia</option>
            <option value='222-Mauritânia'>Mauritânia</option>
            <option value='52-México'>México</option>
            <option value='95-Mianmar'>Mianmar</option>
            <option value='258-Moçambique'>Moçambique</option>
            <option value='373-Moldávia'>Moldávia</option>
            <option value='377-Mônaco'>Mônaco</option>
            <option value='976-Mongólia'>Mongólia</option>
            <option value='1-Monserrate'>Monserrate</option>
            <option value='382-Montenegro'>Montenegro</option>
            <option value='264-Namíbia'>Namíbia</option>
            <option value='674-Nauru'>Nauru</option>
            <option value='977-Nepal'>Nepal</option>
            <option value='505-Nicarágua'>Nicarágua</option>
            <option value='227-Níger'>Níger</option>
            <option value='234-Nigéria'>Nigéria</option>
            <option value='683-Niue'>Niue</option>
            <option value='47-Noruega'>Noruega</option>
            <option value='687-Nova Caledônia'>Nova Caledônia</option>
            <option value='64-Nova Zelândia'>Nova Zelândia</option>
            <option value='968-Omã'>Omã</option>
            <option value='31-Países Baixos'>Países Baixos</option>
            <option value='680-Palau'>Palau</option>
            <option value='970-Palestina'>Palestina</option>
            <option value='507-Panamá'>Panamá</option>
            <option value='675-Papua-Nova Guiné'>Papua-Nova Guiné</option>
            <option value='92-Paquistão'>Paquistão</option>
            <option value='595-Paraguai'>Paraguai</option>
            <option value='51-Peru'>Peru</option>
            <option value='689-Polinésia Francesa'>Polinésia Francesa</option>
            <option value='48-Polônia'>Polônia</option>
            <option value='1-Porto Rico'>Porto Rico</option>
            <option value='351-Portugal'>Portugal</option>
            <option value='254-Quênia'>Quênia</option>
            <option value='996-Quirguistão'>Quirguistão</option>
            <option value='686-Quiribáti'>Quiribáti</option>
            <option value='44-Reino Unido'>Reino Unido</option>
            <option value='236-República Centro-Africana'>República Centro-Africana</option>
            <option value='1-República Dominicana'>República Dominicana</option>
            <option value='262-Reunião'>Reunião</option>
            <option value='40-Romênia'>Romênia</option>
            <option value='250-Ruanda'>Ruanda</option>
            <option value='7-Rússia'>Rússia</option>
            <option value='212-Saara Ocidental'>Saara Ocidental</option>
            <option value='685-Samoa'>Samoa</option>
            <option value='1-Samoa Americana'>Samoa Americana</option>
            <option value='290-Santa Helena'>Santa Helena</option>
            <option value='1-Santa Lúcia'>Santa Lúcia</option>
            <option value='1-São Cristóvão e Neves'>São Cristóvão e Neves</option>
            <option value='378-São Marinho'>São Marinho</option>
            <option value='508-São Pedro e Miquelão'>São Pedro e Miquelão</option>
            <option value='239-São Tomé e Príncipe'>São Tomé e Príncipe</option>
            <option value='1-São Vicente e Granadinas'>São Vicente e Granadinas</option>
            <option value='248-Seicheles'>Seicheles</option>
            <option value='221-Senegal'>Senegal</option>
            <option value='94-Seri Lanca'>Seri Lanca</option>
            <option value='232Serra Leoa'>Serra Leoa</option>
            <option value='381-Sérvia'>Sérvia</option>
            <option value='65-Singapura'>Singapura</option>
            <option value='963-Síria'>Síria</option>
            <option value='252-Somália'>Somália</option>
            <option value='249-Sudão'>Sudão</option>
            <option value='211-Sudão do Sul'>Sudão do Sul</option>
            <option value='46-Suécia'>Suécia</option>
            <option value='41-Suíça'>Suíça</option>
            <option value='597-Suriname'>Suriname</option>
            <option value='66-Tailândia'>Tailândia</option>
            <option value='886-Taiwan'>Taiwan</option>
            <option value='992-Tajiquistão'>Tajiquistão</option>
            <option value='255-Tanzânia'>Tanzânia</option>
            <option value='420-Tchéquia'>Tchéquia</option>
            <option value='246-Território Britânico do Oceano Índico'>Território Britânico do Oceano Índico</option>
            <option value='670-Timor-Leste'>Timor-Leste</option>
            <option value='228-Togo'>Togo</option>
            <option value='676-Tonga'>Tonga</option>
            <option value='690-Toquelau'>Toquelau</option>
            <option value='1-Trindade e Tobago'>Trindade e Tobago</option>
            <option value='216-Tunísia'>Tunísia</option>
            <option value='1-Turcas e Caicos'>Turcas e Caicos</option>
            <option value='993-Turcomenistão'>Turcomenistão</option>
            <option value='90-Turquia'>Turquia</option>
            <option value='688-Tuvalu'>Tuvalu</option>
            <option value='380-Ucrânia'>Ucrânia</option>
            <option value='256-Uganda'>Uganda</option>
            <option value='598-Uruguai'>Uruguai</option>
            <option value='998-Uzbequistão'>Uzbequistão</option>
            <option value='678-Vanuatu'>Vanuatu</option>
            <option value='379-Vaticano'>Vaticano</option>
            <option value='58-Venezuela'>Venezuela</option>
            <option value='84-Vietnã'>Vietnã</option>
            <option value='681-Wallis e Futuna'>Wallis e Futuna</option>
            <option value='260-Zâmbia'>Zâmbia</option>
            <option value='263-Zimbábue'>Zimbábue</option>
            @endforeach
      </select>
    </div>
    <div class="col">
      <label for="code" class="col-sm-8 control-label">Número de contato</label>
      <input type="text" class="form-control" id="number" name="number" value="{{ @$project->number }}">
    </div>
  </div>
  <div>
  <button type="submit" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Salvar</button>
  </div>
</div>